### ISSUE TITLE
PaperTrail Bridge needs eager_load = true

### ISSUE THREAD

**Issue by Ladeburger** [activescaffold/active_scaffold#378]
Hi

The Papertrail-Bridge need the Option
```
config.eager_load = true
```
in the environment configuration, otherwise i get this Error:
```
No route matches {:action => "deleted", :controller => "projects" }
```
Where projects is the name of an Controller with ```has_paper_trail``` in the Model. If this is the normal behaviour, an Comment in the Documentation would be nice.

Thank You

**Comment by scambra** [comment]
When do you get that error?

**Comment by vtt** [comment]
I'm getting the same error as well.  This error can be re-reproduce by using gem "paper_trail", add "has_paper_trail" in the model, and use ActiveScaffold controller listing of the model.

Changing config.eager_load = true makes the error go away.

It seems the paper_trail bridge is only loaded when eager_load = true.

**Comment by scambra** [comment]
Then, is it failing on development?

**Comment by vtt** [comment]
Yes, it fails on default development; if eager_loading = true is set in development, then it works

**Comment by scambra** [comment]
can you test if it fixes development environment?

**Comment by incubus** [comment]
Hi!

  Yep, it fixes ```No route matches {:action => "deleted"``` error. But then I get this error:

```
No route matches {:action=>"index", :association=>:versions, :controller=>"paper_trail/versions", :id=>nil, :item_id=>"--ID--", :parent_scaffold=>"items"}
```

**Comment by incubus** [comment]
```
ActionController::UrlGenerationError - No route matches {:action=>"index", :association=>:versions, :controller=>"paper_trail/versions", :id=>nil, :item_id=>"--ID--", :parent_scaffold=>"items"}:
  actionpack (4.2.0) lib/action_dispatch/journey/formatter.rb:46:in `generate'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:710:in `generate'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:741:in `generate'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:784:in `url_for'
  actionpack (4.2.0) lib/action_dispatch/routing/url_for.rb:156:in `url_for'
  actionview (4.2.0) lib/action_view/routing_url_for.rb:94:in `url_for'
   () Users/incubus/.rvm/gems/ruby-2.2.0/bundler/gems/active_scaffold-d2c4d7d318d2/lib/active_scaffold/helpers/view_helpers.rb:243:in `cached_action_link_url'
   () Users/incubus/.rvm/gems/ruby-2.2.0/bundler/gems/active_scaffold-d2c4d7d318d2/lib/active_scaffold/helpers/view_helpers.rb:278:in `action_link_url'
   () Users/incubus/.rvm/gems/ruby-2.2.0/bundler/gems/active_scaffold-d2c4d7d318d2/lib/active_scaffold/helpers/view_helpers.rb:166:in `render_action_link'
   () Users/incubus/.rvm/gems/ruby-2.2.0/bundler/gems/active_scaffold-d2c4d7d318d2/lib/active_scaffold/helpers/view_helpers.rb:150:in `display_action_link'
   () Users/incubus/.rvm/gems/ruby-2.2.0/bundler/gems/active_scaffold-d2c4d7d318d2/lib/active_scaffold/helpers/view_helpers.rb:129:in `block in display_action_links'
   () Users/incubus/.rvm/gems/ruby-2.2.0/bundler/gems/active_scaffold-d2c4d7d318d2/lib/active_scaffold/data_structures/action_links.rb:105:in `block in each'
   () Users/incubus/.rvm/gems/ruby-2.2.0/bundler/gems/active_scaffold-d2c4d7d318d2/lib/active_scaffold/data_structures/action_links.rb:98:in `each'
   () Users/incubus/.rvm/gems/ruby-2.2.0/bundler/gems/active_scaffold-d2c4d7d318d2/lib/active_scaffold/helpers/view_helpers.rb:115:in `display_action_links'
   () Users/incubus/.rvm/gems/ruby-2.2.0/bundler/gems/active_scaffold-d2c4d7d318d2/lib/active_scaffold/bridges/paper_trail/helper.rb:12:in `display_action_links'
   () Users/incubus/.rvm/gems/ruby-2.2.0/bundler/gems/active_scaffold-d2c4d7d318d2/app/views/active_scaffold_overrides/_list_record.html.erb:24:in `___sers_incubus__rvm_gems_ruby_______bundler_gems_active_scaffold_d_c_d_d___d__app_views_active_scaffold_overrides__list_record_html_erb___253873002727534043_70155376969900'
  actionview (4.2.0) lib/action_view/template.rb:145:in `block in render'
```

**Comment by incubus** [comment]
Nevermind, I forgot to add   

```
namespace :paper_trail do
    resources :versions do as_routes end
 end
```

to routes.rb

**Comment by scambra** [comment]
I'm thinking it could be better to do a gem for this, and include there a paper_trail/versions controller and those routes, then bridge should be removed

**Comment by incubus** [comment]
Nice idea. Is it possible with current architecture of AS?

BTW, this code from the wiki page:

```
  def do_show
    super
    @record = @record.reify
  end
```
gives ```NoMethodError - undefined method `event'``` error.

Is there any way to reload columns configuration for the restored record? Thanks!

**Comment by scambra** [comment]
module PaperTrail::VersionsHelper
  def active_scaffold_config
    @record ? active_scaffold_config_for(@record.class) : super
  end
end

**Comment by incubus** [comment]
It works, thanks!
