### ISSUE TITLE
Embedded Scaffold No Route Error

### ISSUE THREAD

**Issue by blmundie** [activescaffold/active_scaffold#476]
On embedded scaffold I get the following error `No route matches {"action"=>"new", "controller"=>"customers", "eid"=>"cf6988c288f86281e5b640eeac3e7354"} missing required keys: [:controller]`.

    actionpack (4.2.5.1) lib/action_dispatch/journey/formatter.rb:46:in `generate'
    actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:719:in `generate'
    actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:750:in `generate'
    actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:797:in `url_for'
    actionpack (4.2.5.1) lib/action_dispatch/routing/url_for.rb:156:in `url_for'
    actionview (4.2.5.1) lib/action_view/routing_url_for.rb:94:in `url_for'
    active_scaffold (3.4.29) lib/active_scaffold/helpers/view_helpers.rb:243:in `cached_action_link_url'
    active_scaffold (3.4.29) lib/active_scaffold/helpers/view_helpers.rb:276:in `action_link_url'
    active_scaffold (3.4.29) lib/active_scaffold/helpers/view_helpers.rb:163:in `render_action_link'
    active_scaffold (3.4.29) lib/active_scaffold/helpers/view_helpers.rb:147:in `display_action_link'
    active_scaffold (3.4.29) lib/active_scaffold/helpers/view_helpers.rb:126:in `block in display_action_links'
    active_scaffold (3.4.29) lib/active_scaffold/data_structures/action_links.rb:107:in `block in each'
    active_scaffold (3.4.29) lib/active_scaffold/data_structures/action_links.rb:100:in `each'
    active_scaffold (3.4.29) lib/active_scaffold/data_structures/action_links.rb:100:in `each'
    active_scaffold (3.4.29) lib/active_scaffold/helpers/view_helpers.rb:112:in `display_action_links'
    active_scaffold (3.4.29) app/views/active_scaffold_overrides/_list_header.html.erb:4:in `__usr_local_rbenv_versions_______lib_ruby_gems_______gems_active_scaffold________app_views_active_scaffold_overrides__list_header_html_erb___1121107067792583888_69974270831860'

**Comment by blmundie** [comment]
It was a conflict with another gem.
