### ISSUE TITLE
rails 4: Asset was not declared to be precompiled in production

### ISSUE THREAD

**Issue by courtland** [activescaffold/active_scaffold#477]
In rails 4.2, I receive the following error about my asset pipeline configuration.

```log
ActionView::Template::Error (Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( active_scaffold/indicator.gif )` to `config/initializers/assets.rb` and restart your server)
```

If I add the config line to my assets.rb it fixes the problem, but I think this should be configured by active_scaffold? This did not happen to my app under rails 3.2.x. Is there something I am missing?

Here is the full backtrace:

```log
[127.0.0.1] Started GET "/admin/scaffolds/admins/" for 127.0.0.1 at 2016-02-03 09:56:38 -0800
[127.0.0.1] Processing by Admin::Scaffolds::AdminsController#index as HTML
[127.0.0.1]   AdminControllerAcl Load (0.1ms)  SELECT  "admin_controller_acls".* FROM "admin_controller_acls" WHERE (active = 't')  ORDER BY "admin_controller_acls"."id" ASC LIMIT 1
[127.0.0.1]   Admin Load (0.1ms)  SELECT  "admins".* FROM "admins"  ORDER BY "admins"."id" ASC LIMIT 1
[127.0.0.1]   Admin Load (0.1ms)  SELECT  "admins".* FROM "admins" WHERE "admins"."login" = ? AND "admins"."id" = ?  ORDER BY "admins"."id" ASC LIMIT 1  [["login", "ncr"], ["id", 1]]
[127.0.0.1]   AdminRole Load (0.1ms)  SELECT  "admin_roles".* FROM "admin_roles" WHERE "admin_roles"."id" = ? LIMIT 1  [["id", 1]]
[127.0.0.1]    (0.1ms)  SELECT COUNT(*) FROM "admins" WHERE ((radius_realm_id IS NULL) AND (tacacs_realm_id IS NULL))
[127.0.0.1]   Rendered vendor/cache/active_scaffold-12be0838d56e/app/views/active_scaffold_overrides/_list_header.html.erb (6.1ms)
[127.0.0.1]   Rendered vendor/cache/active_scaffold-12be0838d56e/app/views/active_scaffold_overrides/_list_with_header.html.erb (8.6ms)
[127.0.0.1]   Rendered vendor/cache/active_scaffold-12be0838d56e/app/views/active_scaffold_overrides/list.html.erb within layouts/admin/scaffolds (11.2ms)
[127.0.0.1] Completed 500 Internal Server Error in 28ms (ActiveRecord: 0.6ms)
[127.0.0.1] 
ActionView::Template::Error (Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( active_scaffold/indicator.gif )` to `config/initializers/assets.rb` and restart your server):
    2:   unless action_links.empty? -%>
    3:   <div class="actions">
    4:     <%= display_action_links(action_links, nil, :skip_unauthorized => true) %>
    5:     <%= loading_indicator_tag(:action => :table) %>
    6:   </div>
    7: <% end %>
    8: <h2><%= active_scaffold_config.list.user.label %></h2>
  sprockets-rails (3.0.1) lib/sprockets/rails/helper.rb:350:in `raise_unless_precompiled_asset'
  sprockets-rails (3.0.1) lib/sprockets/rails/helper.rb:317:in `asset_path'
  sprockets-rails (3.0.1) lib/sprockets/rails/helper.rb:90:in `block in resolve_asset_path'
  sprockets-rails (3.0.1) lib/sprockets/rails/helper.rb:230:in `block in resolve_asset'
  sprockets-rails (3.0.1) lib/sprockets/rails/helper.rb:229:in `each'
  sprockets-rails (3.0.1) lib/sprockets/rails/helper.rb:229:in `detect'
  sprockets-rails (3.0.1) lib/sprockets/rails/helper.rb:229:in `resolve_asset'
  sprockets-rails (3.0.1) lib/sprockets/rails/helper.rb:89:in `resolve_asset_path'
  sprockets-rails (3.0.1) lib/sprockets/rails/helper.rb:79:in `compute_asset_path'
  actionview (4.2.5.1) lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'
  actionview (4.2.5.1) lib/action_view/helpers/asset_url_helper.rb:292:in `image_path'
  actionview (4.2.5.1) lib/action_view/helpers/asset_tag_helper.rb:211:in `image_tag'
  vendor/cache/active_scaffold-12be0838d56e/lib/active_scaffold/helpers/view_helpers.rb:71:in `loading_indicator_tag'
  vendor/cache/active_scaffold-12be0838d56e/app/views/active_scaffold_overrides/_list_header.html.erb:5:in `_vendor_cache_active_scaffold___be____d__e_app_views_active_scaffold_overrides__list_header_html_erb__1186282229166221753_70151133087600'
  actionview (4.2.5.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5.1) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.5.1) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.5.1) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:21:in `render'
  actionview (4.2.5.1) lib/action_view/helpers/rendering_helper.rb:32:in `render'
  vendor/cache/active_scaffold-12be0838d56e/lib/active_scaffold/extensions/action_view_rendering.rb:119:in `render_with_active_scaffold'
  vendor/cache/active_scaffold-12be0838d56e/app/views/active_scaffold_overrides/_list_with_header.html.erb:3:in `_vendor_cache_active_scaffold___be____d__e_app_views_active_scaffold_overrides__list_with_header_html_erb___801292892455366403_70151133027840'
  actionview (4.2.5.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5.1) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.5.1) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.5.1) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:21:in `render'
  actionview (4.2.5.1) lib/action_view/helpers/rendering_helper.rb:32:in `render'
  vendor/cache/active_scaffold-12be0838d56e/lib/active_scaffold/extensions/action_view_rendering.rb:119:in `render_with_active_scaffold'
  vendor/cache/active_scaffold-12be0838d56e/app/views/active_scaffold_overrides/list.html.erb:1:in `_vendor_cache_active_scaffold___be____d__e_app_views_active_scaffold_overrides_list_html_erb___4149728414388976901_70151132829140'
  actionview (4.2.5.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.5.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.5.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.5.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.5.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.5.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.5.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/nick/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.2.5.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.5.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  vendor/cache/active_scaffold-12be0838d56e/lib/active_scaffold/extensions/action_controller_rendering.rb:14:in `render_with_active_scaffold'
  vendor/cache/active_scaffold-12be0838d56e/lib/active_scaffold/actions/list.rb:37:in `list_respond_to_html'
  vendor/cache/active_scaffold-12be0838d56e/lib/active_scaffold/actions/core.rb:380:in `block (3 levels) in respond_to_action'
  actionpack (4.2.5.1) lib/action_controller/metal/mime_responds.rb:217:in `call'
  actionpack (4.2.5.1) lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
  vendor/cache/active_scaffold-12be0838d56e/lib/active_scaffold/actions/core.rb:376:in `respond_to_action'
  vendor/cache/active_scaffold-12be0838d56e/lib/active_scaffold/actions/list.rb:30:in `list'
  vendor/cache/active_scaffold-12be0838d56e/lib/active_scaffold/actions/list.rb:12:in `index'
  actionpack (4.2.5.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.5.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:815:in `call'
  rack-mobile-detect (0.4.0) lib/rack/mobile-detect.rb:164:in `call'
  http_accept_language (2.0.5) lib/http_accept_language/middleware.rb:14:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack-xml_parser (1.0.2) lib/action_dispatch/xml_params_parser.rb:16:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5.1) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.4) lib/thin/connection.rb:84:in `catch'
  thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.4) lib/thin/connection.rb:53:in `process'
  thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
  eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
  thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.4) lib/thin/server.rb:162:in `start'
  rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.5.1) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.5.1) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.5.1) lib/rails/commands/commands_tasks.rb:75:in `tap'
  railties (4.2.5.1) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.5.1) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.5.1) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<main>'
```

**Comment by naaano** [comment]
no, you´re right. I didn´t report this bug before, i fixed by adding this in an initializer:
```
Rails.application.config.assets.precompile += %w( active_scaffold/indicator.gif )
```
nasty, right? 

This is the only image used by AS.

**Comment by scambra** [comment]
Not the only, it has these icons too: add.png  arrow_down.png  arrow_up.png  close.png  close_touch.png  config.png  cross.png  gears.png  indicator-small.gif  magnifier.png  refresh.png

But they are used on scss files, so probably sprockets is precompiling them

**Comment by scambra** [comment]
Let me know if still fails

**Comment by courtland** [comment]
It works now. Thanks!
