### ISSUE TITLE
Version 3.4.2 breaks some has_many :through behavior in Rails 4.2.6

### ISSUE THREAD

**Issue by hoffm** [activescaffold/active_scaffold#491]
### Summary

In upgrading a Rails app from the 4.0 series to 4.2.6, I found an incompatibility between recent versions of Active Scaffold and Active Record 4.2.6. I conducted a binary search on earlier versions of Active Scaffold and determined that the incompatibility with Rails 4.2.6 was introduced in Active Scaffold 3.4.2. 

### To Reproduce

Create a Rails 4.2.6 app with active_scaffold 3.4.2 or later installed (in the example below I use v3.4.35).  Add a `has_many`, `through` association. E.g.:

``` ruby
class CollectionsCollectable < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :collection
end

class Collection < ActiveRecord::Base
  has_many :collections_collectables
  has_many :recipes, through: :collections_collectables
end

class Recipe < ActiveRecord::Base
  has_many :collections_collectables
  has_many :collections, through: :collections_collectables
end
```

Use conventional names for the foreign key columns in each table.

Fire up a rails console and try to add a recipe to a collection using the `<<` method, like so: `collection.recipes << recipe`. The correct `INSERT` query is generated, but it is rolled back when an exception is thrown:

```
> collection.recipes << recipe
   (0.1ms)  BEGIN
  SQL (1.9ms)  INSERT INTO `collections_collectables` (`collection_id`, `recipe_id`, `created_at`, `updated_at`) VALUES (173149, 12345, '2016-04-04 16:33:15', '2016-04-04 16:33:15')
   (0.7ms)  ROLLBACK
NoMethodError: undefined method `class_name' for nil:NilClass
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/reflection.rb:883:in `derive_class_name'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/reflection.rb:157:in `class_name'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/active_scaffold-3.4.35/lib/active_scaffold/extensions/reverse_associations.rb:97:in `block in reverse_matches'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/active_scaffold-3.4.35/lib/active_scaffold/extensions/reverse_associations.rb:93:in `each'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/active_scaffold-3.4.35/lib/active_scaffold/extensions/reverse_associations.rb:93:in `reverse_matches'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/active_scaffold-3.4.35/lib/active_scaffold/extensions/reverse_associations.rb:30:in `autodetect_inverse'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/active_scaffold-3.4.35/lib/active_scaffold/extensions/reverse_associations.rb:10:in `inverse_of_with_autodetect'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/associations/has_many_association.rb:148:in `inverse_updates_counter_in_memory?'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/associations/has_many_association.rb:152:in `counter_must_be_updated_by_has_many?'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/associations/has_many_association.rb:115:in `update_counter_in_memory'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/associations/has_many_association.rb:193:in `update_counter_if_success'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/associations/has_many_association.rb:180:in `concat_records'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/associations/has_many_through_association.rb:44:in `concat_records'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:168:in `block in concat'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:183:in `block in transaction'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:182:in `transaction'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:168:in `concat'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/associations/has_many_through_association.rb:38:in `concat'
	from /Users/hoffm/.rvm/gems/ruby-1.9.3-p551@food52/gems/activerecord-4.2.6/lib/active_record/associations/collection_proxy.rb:970:in `<<'
```

### More Details

After discovering the incompatibility with the most recent versions of Active Scaffold, I went back to try to determine when it was introduced. I discovered that I could not reproduce the error in version 3.4.0. I then performed a binary search to determine when the error was introduced. Note that I made the assumption that there was some version after which the error was always reproducible, and before which it never was.

I created a test for the issue and ran it against many version of Active Scaffold. Here are the results:

3.4.0 PASS
3.4.1 PASS
3.4.2 FAIL
3.4.3 FAIL
3.4.5 FAIL
3.4.10 FAIL
3.4.11 FAIL
3.4.33 FAIL
3.4.35 FAIL

I therefore conjecture that the error was introduced in Active Scaffold 3.4.2.

Note that I'm using ruby version 1.9.3-p551. Note also that this error cannot be reproduced against the latest versions of Rails in the 4.0 series.

### And Finally

Thanks to @newsomc for investigating this with me.

**Comment by scambra** [comment]
Not sure it's a bug in ActiveScaffold, ActiveScaffold is calling class_name in has_many through reflection. You can get this error in rails console without ActiveScaffold, calling:
Collection.reflect_on_association(:recipes).class_name
Recipe.reflect_on_association(:collections).class_name
It fails because it can't find source_reflection

**Comment by hoffm** [comment]
@scambra I agree with that you can reproduce the error that way, but that's been true in ActiveRecord at least as far back as 3.2. Even if you're saying that this behavior is an ActiveRecord bug (which I"m not sure that it is), shouldn't ActiveScaffold work around it? As far as I can tell, one cannot use ActiveScaffold versions newer than 3.4.1 in apps that use `has_many, :through` associations. That seems bad.

**Comment by scambra** [comment]
has_many through is working for me with rails 4.2.6, and reflect_on_association(hmt_assoc).class_name works too, so not sure there is a bug in ActiveScaffold there. I don't know why your associations doesn't have source_reflection, they look right to me, but rails usually failed to use has_many through if source reflection was not found, so I don't understand how your associations are working without source_reflection.

Can you test those lines, or adding a record in rails console, after removing ActiveScaffold from gemfile?

**Comment by scambra** [comment]
Maybe related, I was trying to reproduce your error, and trying to generate collection model I get this error:
```
$rails g model collection name:string
      invoke  active_record
The name 'Collection' is either already used in your application or reserved by Ruby on Rails. Please choose an alternative and run this generator again.

**Comment by scambra** [comment]
Can you verify issue is related to model named Collection?
