### ISSUE TITLE
UnknownPrimaryKey-Exception in has_may :through

### ISSUE THREAD

**Issue by Ladeburger** [activescaffold/active_scaffold#522]
Rails 5.0.0.1
Ruby 2.3.1
AS 3.4.41.1

I try to use AS for an Legacy-Datamodel which has m:n - Relations with additional Informations. So
i want to use has_many : through - Relations Problem is, the Relations have no primary Key. So far,
everything is working fine, except when i want to access an Object from the m:n relation.

Example:
System
  has_many :patchassingnments
  has_many :patches, :through => :patchassignments

Patch
  has_many :patchassingnments
  has_many :systems, :through => :patchassignments

Patchassignment
  belongs_to :system
  belongs_to :patch

Listing of Systems: Work
Sublisting of Patchassignments: Work
Hitting an Patch in the Sublisting: Error
```

Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)


  
ActiveRecord::UnknownPrimaryKey (Unknown primary key for table patchassignments in model Patchassignment.):
  
activerecord (5.0.0.1) lib/active_record/relation/finder_methods.rb:445:in `find_with_ids'
activerecord (5.0.0.1) lib/active_record/relation/finder_methods.rb:66:in `find'
activerecord (5.0.0.1) lib/active_record/querying.rb:3:in `find'
activerecord (5.0.0.1) lib/active_record/core.rb:151:in `find'
/home/jan/.bundle/ruby/2.2.0/active_scaffold-fdd479d7f3e4/lib/active_scaffold/finder.rb:371:in `find_if_allowed'
/home/jan/.bundle/ruby/2.2.0/active_scaffold-fdd479d7f3e4/lib/active_scaffold/actions/nested.rb:108:in `nested_parent_record'
/home/jan/.bundle/ruby/2.2.0/active_scaffold-fdd479d7f3e4/lib/active_scaffold/helpers/id_helpers.rb:14:in `nested_parent_id'
/home/jan/.bundle/ruby/2.2.0/active_scaffold-fdd479d7f3e4/lib/active_scaffold/actions/core.rb:243:in `active_scaffold_session_storage_key'
/home/jan/.bundle/ruby/2.2.0/active_scaffold-fdd479d7f3e4/lib/active_scaffold/actions/core.rb:248:in `active_scaffold_session_storage'
/home/jan/.bundle/ruby/2.2.0/active_scaffold-fdd479d7f3e4/lib/active_scaffold/constraints.rb:11:in `active_scaffold_constraints'
/home/jan/.bundle/ruby/2.2.0/active_scaffold-fdd479d7f3e4/lib/active_scaffold/constraints.rb:20:in `register_constraints_with_action_columns'
/home/jan/.bundle/ruby/2.2.0/active_scaffold-fdd479d7f3e4/lib/active_scaffold/actions/nested.rb:31:in `set_nested'
/home/jan/.bundle/ruby/2.2.0/active_scaffold-fdd479d7f3e4/lib/active_scaffold/actions/nested.rb:19:in `nested'
/home/jan/.bundle/ruby/2.2.0/active_scaffold-fdd479d7f3e4/lib/active_scaffold/actions/nested.rb:24:in `nested?'
/home/jan/.bundle/ruby/2.2.0/active_scaffold-fdd479d7f3e4/lib/active_scaffold/actions/core.rb:243:in `active_scaffold_session_storage_key'
/home/jan/.bundle/ruby/2.2.0/active_scaffold-fdd479d7f3e4/lib/active_scaffold/actions/core.rb:248:in `active_scaffold_session_storage'
/home/jan/.bundle/ruby/2.2.0/active_scaffold-fdd479d7f3e4/lib/active_scaffold/actions/core.rb:260:in `handle_user_settings'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:169:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:12:in `call'
```

**Comment by Atastor** [comment]
Isn't this more of a Rails problem, than an AS problem?

**Comment by Atastor** [comment]
Something like this might help: [https://github.com/composite-primary-keys/composite_primary_keys]

**Comment by Ladeburger** [comment]
For the Model, everythin working fine:
```
irb(main):004:0> s = System.find(15).patchassignments.first.patch
  System Load (0.6ms)  SELECT  "systems".* FROM "systems" WHERE "systems"."id" = $1 LIMIT $2  [["id", 15], ["LIMIT", 1]]
  Patchassignment Load (0.4ms)  SELECT  "patchassignments".* FROM "patchassignments" WHERE "patchassignments"."system_id" = $1 LIMIT $2  [["system_id", 15], ["LIMIT", 1]]
  Patch Load (0.4ms)  SELECT  "patches".* FROM "patches" WHERE "patches"."id" = $1 LIMIT $2  [["id", 13], ["LIMIT", 1]]
=> #<Patch id: 13, name: "Patch_2", description: "This is Patch 2, which is very important">
irb(main):005:0>
```
I already read about composite-primary-keys but try to avoid them if it is not really neccessary

**Comment by scambra** [comment]
Could you post first lines of request in log?
You are not using 3.4.41.1, you are using activescaffold from master, but it should work anyway

**Comment by Ladeburger** [comment]
```
Started GET "/patches/16/edit?association=patch&parent_scaffold=patchassignments&patchassignment_id=&adapter=_list_inline_adapter" for 127.0.0.1 at 2016-10-17 11:43:41 +0200
Processing by PatchesController#edit as JS
```
bundle install says this Version, but you are right, i use master, sorry.

**Comment by scambra** [comment]
bundle says that because version file in master was 3.4.41.1, I have changed to 3.4.99

patchassignment_id is missing in url:
/patches/16/edit?association=patch&parent_scaffold=patchassignments&patchassignment_id=&adapter=_list_inline_adapter

What do you get in rails console?
System.find(15).patchassignments.first

**Comment by Ladeburger** [comment]
```
irb(main):001:0> System.find(15).patchassignments.first
  System Load (0.5ms)  SELECT  "systems".* FROM "systems" WHERE "systems"."id" = $1 LIMIT $2  [["id", 15], ["LIMIT", 1]]
  Patchassignment Load (0.4ms)  SELECT  "patchassignments".* FROM "patchassignments" WHERE "patchassignments"."system_id" = $1 LIMIT $2  [["system_id", 15], ["LIMIT", 1]]
=> #<Patchassignment patch_id: 13, system_id: 15>
irb(main):002:0>
```
and if i look deeper:
```
irb(main):002:0> System.find(15).patchassignments.first.patch
  System Load (0.6ms)  SELECT  "systems".* FROM "systems" WHERE "systems"."id" = $1 LIMIT $2  [["id", 15], ["LIMIT", 1]]
  Patchassignment Load (0.4ms)  SELECT  "patchassignments".* FROM "patchassignments" WHERE "patchassignments"."system_id" = $1 LIMIT $2  [["system_id", 15], ["LIMIT", 1]]
  Patch Load (0.5ms)  SELECT  "patches".* FROM "patches" WHERE "patches"."id" = $1 LIMIT $2  [["id", 13], ["LIMIT", 1]]
=> #<Patch id: 13, name: "Patch_2", description: "This is Patch 2, which is very important">
irb(main):003:0>
```

**Comment by scambra** [comment]
Your patchassignments table should have id column if you want to use with has_many :through, but it only has patch_id and system_id. Table without primary key should be used only for has_and_belongs_to_many

**Comment by scambra** [comment]
Also, if you don't have any other columns you can use has_and_belongs_to_many and remove patchassignment model.

```ruby
class System < ActiveRecord::Base
  has_and_belongs_to_many :patches, :join_table => :patchassignments

class Patch < ActiveRecord::Base
  has_and_belongs_to_many :systems, :join_table => :patchassignments

**Comment by Ladeburger** [comment]
scaramba, you are right, but i work with an legacy data model and there are other columns: http://spacewalk.redhat.com/documentation/schema-doc/table-RHNERRATABUGLIST.html
So if understand correct, i have to use composite index as mentioned by Atastor.

Anyway, thank you :-)
