### ISSUE TITLE
Removing a column generates a crash for users who have sorted by that column previously

### ISSUE THREAD

**Issue by ConfusedVorlon** [activescaffold/active_scaffold#525]
1) use active scaffold. Sort by 'spam'
2) remove the column 'spam'
3) try to load the page.

expected:
Active Scaffold ignores cookie telling it to sort by 'spam'

actual:
application crashes!

note - deleting the cookies stops the crash.

```
ArgumentError (Could not find column spam):
  active_scaffold (3.4.35) lib/active_scaffold/data_structures/sorting.rb:36:in `add'
  active_scaffold (3.4.35) lib/active_scaffold/data_structures/sorting.rb:59:in `set'
  active_scaffold (3.4.35) lib/active_scaffold/config/list.rb:271:in `sorting'
  active_scaffold (3.4.35) lib/active_scaffold/actions/list.rb:75:in `set_includes_for_columns'
  active_scaffold (3.4.35) lib/active_scaffold/actions/list.rb:90:in `do_list'
  active_scaffold (3.4.35) lib/active_scaffold/actions/list.rb:26:in `list'
  active_scaffold (3.4.35) lib/active_scaffold/actions/list.rb:12:in `index'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
```

**Comment by scambra** [comment]
How are you removing column?

**Comment by ConfusedVorlon** [comment]
with a migration

**Comment by scambra** [comment]
Fixed only in master branch, not released yet, you will have to use github: 'activescaffold/active_scaffold' in your gemfile to get the fix

**Comment by ConfusedVorlon** [comment]
thank you.
