### ISSUE TITLE
getting "unable to convert unpermitted parameters to hash" in Rails 5.1/Ruby 2.4

### ISSUE THREAD

**Issue by cpg** [activescaffold/active_scaffold#552]
running from master (and i realize there is no support for rails 5.1, so this is only fyi), i am getting:

```
.../2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/app/views/active_scaffold_overrides/_list_record.html.erb where line #15 raised:
unable to convert unpermitted parameters to hash

.../2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/helpers/action_link_helpers.rb:306:in `action_link_selected?'
.../2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/helpers/action_link_helpers.rb:330:in `action_link_html_options'
.../2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/helpers/action_link_helpers.rb:91:in `render_action_link'
.../2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/helpers/list_column_helpers.rb:48:in `render_list_column'
...
```

**Comment by scambra** [comment]
master should work with rails 5, not tested with rails 5.1 yet

Anyway, can you remove backtrace silencers to get more useful trace, exception must be raised in some activescaffold helper

**Comment by cpg** [comment]
verbose ... hope it helps?

```
 Showing /Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/app/views/active_scaffold_overrides/_list_record.html.erb where line #15 raised:

unable to convert unpermitted parameters to hash

Extracted source (around line #258):
        convert_parameters_to_hashes(@parameters, :to_h)
      else
        raise UnfilteredParameters
      end
    end

Trace of template inclusion: /Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/app/views/active_scaffold_overrides/_list.html.erb, /Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/app/views/active_scaffold_overrides/_list_with_header.html.erb, /Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/app/views/active_scaffold_overrides/list.html.erb

actionpack (5.1.0) lib/action_controller/metal/strong_parameters.rb:258:in `to_h'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/helpers/action_link_helpers.rb:306:in `action_link_selected?'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/helpers/action_link_helpers.rb:330:in `action_link_html_options'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/helpers/action_link_helpers.rb:91:in `render_action_link'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/helpers/list_column_helpers.rb:48:in `render_list_column'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/app/views/active_scaffold_overrides/_list_record.html.erb:15:in `block (2 levels) in ___sers_cpg__rbenv_versions_______lib_ruby_gems_______bundler_gems_active_scaffold_c__fee_______app_views_active_scaffold_overrides__list_record_html_erb___837830228347785178_70342825991000'
actionview (5.1.0) lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
actionview (5.1.0) lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
actionview (5.1.0) lib/action_view/helpers/capture_helper.rb:39:in `capture'
actionview (5.1.0) lib/action_view/helpers/tag_helper.rb:272:in `content_tag'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/app/views/active_scaffold_overrides/_list_record.html.erb:14:in `block in ___sers_cpg__rbenv_versions_______lib_ruby_gems_______bundler_gems_active_scaffold_c__fee_______app_views_active_scaffold_overrides__list_record_html_erb___837830228347785178_70342825991000'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/app/views/active_scaffold_overrides/_list_record.html.erb:10:in `each'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/app/views/active_scaffold_overrides/_list_record.html.erb:10:in `___sers_cpg__rbenv_versions_______lib_ruby_gems_______bundler_gems_active_scaffold_c__fee_______app_views_active_scaffold_overrides__list_record_html_erb___837830228347785178_70342825991000'
actionview (5.1.0) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.0) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.0) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.0) lib/action_view/template.rb:155:in `render'
actionview (5.1.0) lib/action_view/renderer/partial_renderer.rb:439:in `block in collection_with_template'
actionview (5.1.0) lib/action_view/renderer/partial_renderer.rb:435:in `map'
actionview (5.1.0) lib/action_view/renderer/partial_renderer.rb:435:in `collection_with_template'
actionview (5.1.0) lib/action_view/renderer/partial_renderer.rb:325:in `block (2 levels) in render_collection'
actionview (5.1.0) lib/action_view/renderer/partial_renderer/collection_caching.rb:13:in `cache_collection_render'
actionview (5.1.0) lib/action_view/renderer/partial_renderer.rb:324:in `block in render_collection'
actionview (5.1.0) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.1.0) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.0) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.0) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.1.0) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.1.0) lib/action_view/renderer/partial_renderer.rb:317:in `render_collection'
actionview (5.1.0) lib/action_view/renderer/partial_renderer.rb:308:in `render'
actionview (5.1.0) lib/action_view/renderer/renderer.rb:47:in `render_partial'
actionview (5.1.0) lib/action_view/renderer/renderer.rb:21:in `render'
actionview (5.1.0) lib/action_view/helpers/rendering_helper.rb:32:in `render'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/extensions/action_view_rendering.rb:110:in `render'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/app/views/active_scaffold_overrides/_list.html.erb:28:in `___sers_cpg__rbenv_versions_______lib_ruby_gems_______bundler_gems_active_scaffold_c__fee_______app_views_active_scaffold_overrides__list_html_erb__2016364000806961804_70342834709480'
actionview (5.1.0) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.0) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.0) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.0) lib/action_view/template.rb:155:in `render'
actionview (5.1.0) lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
actionview (5.1.0) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.1.0) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.0) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.0) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.1.0) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.1.0) lib/action_view/renderer/partial_renderer.rb:331:in `render_partial'
actionview (5.1.0) lib/action_view/renderer/partial_renderer.rb:310:in `render'
actionview (5.1.0) lib/action_view/renderer/renderer.rb:47:in `render_partial'
actionview (5.1.0) lib/action_view/renderer/renderer.rb:21:in `render'
actionview (5.1.0) lib/action_view/helpers/rendering_helper.rb:32:in `render'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/extensions/action_view_rendering.rb:110:in `render'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/app/views/active_scaffold_overrides/_list_with_header.html.erb:34:in `block in ___sers_cpg__rbenv_versions_______lib_ruby_gems_______bundler_gems_active_scaffold_c__fee_______app_views_active_scaffold_overrides__list_with_header_html_erb__845675833493323839_70342849500280'
actionview (5.1.0) lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
actionview (5.1.0) lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
actionview (5.1.0) lib/action_view/helpers/capture_helper.rb:39:in `capture'
actionview (5.1.0) lib/action_view/helpers/tag_helper.rb:272:in `content_tag'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/app/views/active_scaffold_overrides/_list_with_header.html.erb:1:in `___sers_cpg__rbenv_versions_______lib_ruby_gems_______bundler_gems_active_scaffold_c__fee_______app_views_active_scaffold_overrides__list_with_header_html_erb__845675833493323839_70342849500280'
actionview (5.1.0) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.0) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.0) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.0) lib/action_view/template.rb:155:in `render'
actionview (5.1.0) lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
actionview (5.1.0) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.1.0) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.0) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.0) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.1.0) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.1.0) lib/action_view/renderer/partial_renderer.rb:331:in `render_partial'
actionview (5.1.0) lib/action_view/renderer/partial_renderer.rb:310:in `render'
actionview (5.1.0) lib/action_view/renderer/renderer.rb:47:in `render_partial'
actionview (5.1.0) lib/action_view/renderer/renderer.rb:21:in `render'
actionview (5.1.0) lib/action_view/helpers/rendering_helper.rb:32:in `render'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/extensions/action_view_rendering.rb:110:in `render'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/app/views/active_scaffold_overrides/list.html.erb:1:in `___sers_cpg__rbenv_versions_______lib_ruby_gems_______bundler_gems_active_scaffold_c__fee_______app_views_active_scaffold_overrides_list_html_erb___3979486391718380799_70342849556760'
actionview (5.1.0) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.0) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.0) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.0) lib/action_view/template.rb:155:in `render'
actionview (5.1.0) lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
actionview (5.1.0) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.1.0) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.0) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.0) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.1.0) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.1.0) lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
actionview (5.1.0) lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
actionview (5.1.0) lib/action_view/renderer/template_renderer.rb:50:in `render_template'
actionview (5.1.0) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.1.0) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.1.0) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.1.0) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.1.0) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.1.0) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.1.0) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.1.0) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (5.1.0) lib/abstract_controller/rendering.rb:24:in `render'
actionpack (5.1.0) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.1.0) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.1.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
activesupport (5.1.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.1.0) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.1.0) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.1.0) lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
actionpack (5.1.0) lib/action_controller/metal/instrumentation.rb:43:in `render'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/extensions/action_controller_rendering.rb:14:in `render'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/actions/list.rb:37:in `list_respond_to_html'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/actions/core.rb:430:in `block (3 levels) in respond_to_action'
actionpack (5.1.0) lib/action_controller/metal/mime_responds.rb:201:in `respond_to'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/actions/core.rb:426:in `respond_to_action'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/actions/list.rb:30:in `list'
/Users/cpg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/active_scaffold-c59fee889228/lib/active_scaffold/actions/list.rb:12:in `index'
actionpack (5.1.0) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.0) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.0) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.0) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.0) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.0) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.0) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.0) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.0) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.0) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.0) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.0) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.0) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.0) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.0) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.0) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.0) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.0) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.0) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.0) lib/action_dispatch/routing/route_set.rb:832:in `call'
rack (2.0.2) lib/rack/etag.rb:25:in `call'
rack (2.0.2) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.2) lib/rack/head.rb:12:in `call'
rack (2.0.2) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.2) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.0) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.0) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.0) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.0) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.2) lib/rack/method_override.rb:22:in `call'
rack (2.0.2) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.2) lib/rack/sendfile.rb:111:in `call'
railties (5.1.0) lib/rails/engine.rb:522:in `call'
thin (1.7.0) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.7.0) lib/thin/connection.rb:84:in `catch'
thin (1.7.0) lib/thin/connection.rb:84:in `pre_process'
thin (1.7.0) lib/thin/connection.rb:53:in `process'
thin (1.7.0) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.2.3) lib/eventmachine.rb:194:in `run_machine'
eventmachine (1.2.3) lib/eventmachine.rb:194:in `run'
thin (1.7.0) lib/thin/backends/base.rb:73:in `start'
thin (1.7.0) lib/thin/server.rb:162:in `start'
rack (2.0.2) lib/rack/handler/thin.rb:22:in `run'
rack (2.0.2) lib/rack/server.rb:297:in `start'
railties (5.1.0) lib/rails/commands/server/server_command.rb:44:in `start'
railties (5.1.0) lib/rails/commands/server/server_command.rb:130:in `block in perform'
railties (5.1.0) lib/rails/commands/server/server_command.rb:125:in `tap'
railties (5.1.0) lib/rails/commands/server/server_command.rb:125:in `perform'
thor (0.19.4) lib/thor/command.rb:27:in `run'
thor (0.19.4) lib/thor/invocation.rb:126:in `invoke_command'
thor (0.19.4) lib/thor.rb:369:in `dispatch'
railties (5.1.0) lib/rails/command/base.rb:63:in `perform'
railties (5.1.0) lib/rails/command.rb:44:in `invoke'
railties (5.1.0) lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

```

**Comment by scambra** [comment]
I didn't test the fix, I don't have any app with rails 5.1 yet, let me know if still fails

**Comment by scambra** [comment]
You haven't updated version to commit e1be021

**Comment by Atastor** [comment]
At least my 5.1 app now is able to use :has_trough relationships again.

**Comment by cpg** [comment]
It works well. Great job!
