### ISSUE TITLE
undefined method `all?` for ActionController::Parameters

### ISSUE THREAD

**Issue by cpg** [activescaffold/active_scaffold#554]
In a few situations in my Rails 5.1 app (running with a recent AS master), I think only when I am saving a record at least 1-deep with associations, I get this fatal error. I do not think the app is doing something wong, active-scaffold wise, but I am not 100% sure. This seems like a bug, because flat (no association) saves seem to work fine:

```
NoMethodError (undefined method `all?' for #<ActionController::Parameters:0x007fcb9980c6d8>):
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/attribute_params.rb:276:in `attributes_hash_is_empty?'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/attribute_params.rb:232:in `build_record_from_params?'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/attribute_params.rb:218:in `manage_nested_record_from_params'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/attribute_params.rb:206:in `column_value_from_param_hash_value'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/attribute_params.rb:148:in `column_value_from_param_value'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/attribute_params.rb:118:in `update_column_from_params'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/attribute_params.rb:106:in `block in update_record_from_params'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/data_structures/action_columns.rb:88:in `block in each'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/data_structures/action_columns.rb:76:in `each'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/data_structures/action_columns.rb:76:in `each'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/data_structures/action_columns.rb:83:in `block in each'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/data_structures/action_columns.rb:76:in `each'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/data_structures/action_columns.rb:76:in `each'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/attribute_params.rb:96:in `update_record_from_params'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/actions/update.rb:105:in `block in update_save'
activerecord (5.1.0) lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
activerecord (5.1.0) lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/home/cpg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
activerecord (5.1.0) lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
activerecord (5.1.0) lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
activerecord (5.1.0) lib/active_record/transactions.rb:210:in `transaction'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/actions/update.rb:104:in `update_save'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/actions/update.rb:98:in `do_update'
/home/cpg/html/shared/bundle/ruby/2.4.0/bundler/gems/active_scaffold-54a7ccdb6443/lib/active_scaffold/actions/update.rb:14:in `update'
actionpack (5.1.0) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.0) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.0) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
```

**Comment by cpg** [comment]
Works great. Thanks!
