### ISSUE TITLE
Error running cancan bridge: "undefined method authorized_for?"

### ISSUE THREAD

**Issue by guycall** [activescaffold/active_scaffold#559]
I am trying to update an old Rails 3.2 application to 4.2. First step is upgrading to Rails 4.0.13, but I get the following error on application startup:

```
/var/lib/gems/2.3.0/gems/activesupport-4.0.13/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method': undefined method `authorized_for?' for class `ActiveRecord::Base' (NameError)
  from /var/lib/gems/2.3.0/gems/activesupport-4.0.13/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain'
  from /var/lib/gems/2.3.0/gems/active_scaffold-3.4.41.1/lib/active_scaffold/bridges/cancan/cancan_bridge.rb:108:in `block in <module:ActiveRecord>'
  from /var/lib/gems/2.3.0/gems/activesupport-4.0.13/lib/active_support/concern.rb:114:in `class_eval'
  from /var/lib/gems/2.3.0/gems/activesupport-4.0.13/lib/active_support/concern.rb:114:in `append_features'
  from /var/lib/gems/2.3.0/gems/active_scaffold-3.4.41.1/lib/active_scaffold/bridges/cancan.rb:11:in `include'
  from /var/lib/gems/2.3.0/gems/active_scaffold-3.4.41.1/lib/active_scaffold/bridges/cancan.rb:11:in `install'
  from /var/lib/gems/2.3.0/gems/active_scaffold-3.4.41.1/lib/active_scaffold/data_structures/bridge.rb:16:in `run'
  from /var/lib/gems/2.3.0/gems/active_scaffold-3.4.41.1/lib/active_scaffold/bridges.rb:39:in `block in run_all'
  from /var/lib/gems/2.3.0/gems/active_scaffold-3.4.41.1/lib/active_scaffold/bridges.rb:37:in `each'
  from /var/lib/gems/2.3.0/gems/active_scaffold-3.4.41.1/lib/active_scaffold/bridges.rb:37:in `run_all'
  from /vagrant/myapp/config/initializers/active_scaffold.rb:5:in `<top (required)>'
```

My key files are:
```
#config/initializers/active_scaffold.rb
ActiveScaffold::Bridges.run_all
```

```
#app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    return nil unless user
    as_action_aliases # ActiveScaffold
...
```

The key gems I am updating to:
```
rails (3.2.22.5) -> rails (4.0.13)
active_scaffold (3.3.3) -> active_scaffold (3.4.41.1)
cancancan (1.15.0) -> cancancan (1.16.0)
```

If I step through the code of `ActiveScaffold::Bridges.run_all` I hit the error here:

``` 
[32, 41] in /var/lib/gems/2.3.0/gems/active_scaffold-3.4.41.1/lib/active_scaffold/bridges.rb
   32:       alias_method :[], :load
   33:     end
   34: 
   35:     def self.run_all
   36:       return false if bridges_run
=> 37:       bridges.keys.each do |bridge_name|
   38:         bridge = self[bridge_name]
   39:         bridge.run if bridge
   40:       end
   41:       self.bridges_run = true
(byebug) bridges.keys
[:ancestry, :tiny_mce, :usa_state_select, :paper_trail, :cancan, :dragonfly, :date_picker, :record_select, :country_select, :calendar_date_select, :chosen, :paperclip, :carrierwave, :semantic_attributes, :bitfields, :file_column]
(byebug) self[:cancan].run
*** NameError Exception: undefined method `authorized_for?' for class `ActiveRecord::Base'

nil
(byebug) self[:cancan].run
ActiveRecord::Base
```

What is interesting is the second time I call ` self[:cancan].run` it works.

**Comment by scambra** [comment]
why are you running ActiveScaffold::Bridges.run_all in initializer? It looks like initializer is run before authorized_for? method is added to activerecord, which is does when activerecord is loaded with ActiveSupport.on_load hook, probably it was doing in different way in previous activescaffold version, or rails changed when initializers are run.

ActiveScaffold run run_all when first controller using active_scaffold is loaded, and authorized_for? is already added to ActiveRecord::Base in that time

**Comment by guycall** [comment]
Thanks for the reply. This is a project I inherited, so I am not sure why `run_all` was in initializer. It was setup originally with active_scaffold (3.2.x).

Anyways, thank you the reply. It is greatly appreciated.
