### ISSUE TITLE
uninitialized constant Jquery

### ISSUE THREAD

**Issue by duderonomy** [activescaffold/active_scaffold#596]
I've updated my Ruby on Rails environment to
```
#  rails -v
Rails 5.2.0
# ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
```
ActiveScaffold version:
```
# grep active_scaffold Gemfile.lock 
    active_scaffold (3.5.1)
  active_scaffold
```
Steps:
Followed instructions for Rails 5, in Readme.
Load in browser: http://localhost:3000/users
Error:
```
Showing ${HOME}/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/active_scaffold-3.5.1/app/views/active_scaffold_overrides/_list_header.html.erb where line #5 raised:

uninitialized constant Jquery

Extracted source (around line #53):
            # If the constant was actually loaded, something else went wrong?
            raise if from_mod.const_defined?(const_name)
            CoreExt::ActiveSupport.without_bootsnap_cache { super }
          end

          # Signature has changed a few times over the years; easiest to not

```

Stack trace:
```
Trace of template inclusion: ${HOME}/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/active_scaffold-3.5.1/app/views/active_scaffold_overrides/_list_with_header.html.erb, ${HOME}/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/active_scaffold-3.5.1/app/views/active_scaffold_overrides/list.html.erb

Rails.root: ${HOME}/Projects/Rails/temp/test_active_scaffold

Application Trace | Framework Trace | Full Trace
bootsnap (1.3.0) lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
bootsnap (1.3.0) lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
bootsnap (1.3.0) lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
bootsnap (1.3.0) lib/bootsnap/load_path_cache/core_ext/active_support.rb:42:in `load_missing_constant'
active_scaffold (3.5.1) app/assets/stylesheets/active_scaffold_jquery_ui.css.erb:1:in `block in singleton class'
active_scaffold (3.5.1) app/assets/stylesheets/active_scaffold_jquery_ui.css.erb:-6:in `instance_eval'
active_scaffold (3.5.1) app/assets/stylesheets/active_scaffold_jquery_ui.css.erb:-6:in `singleton class'
active_scaffold (3.5.1) app/assets/stylesheets/active_scaffold_jquery_ui.css.erb:-9:in `__tilt_70252725220560'
tilt (2.0.8) lib/tilt/template.rb:170:in `call'
tilt (2.0.8) lib/tilt/template.rb:170:in `evaluate'
tilt (2.0.8) lib/tilt/template.rb:109:in `render'
sass-rails (5.0.7) lib/sass/rails/importer.rb:90:in `process_erb_engine'
sass-rails (5.0.7) lib/sass/rails/importer.rb:79:in `find_relative'
sass-rails (5.0.7) lib/sass/rails/importer.rb:18:in `find_relative'
sass (3.5.6) lib/sass/tree/import_node.rb:48:in `import'
sass (3.5.6) lib/sass/tree/import_node.rb:28:in `imported_file'
sass (3.5.6) lib/sass/tree/import_node.rb:37:in `css_import?'
sass (3.5.6) lib/sass/tree/visitors/perform.rb:314:in `visit_import'
sass (3.5.6) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.5.6) lib/sass/tree/visitors/perform.rb:162:in `block in visit'
sass (3.5.6) lib/sass/stack.rb:79:in `block in with_base'
sass (3.5.6) lib/sass/stack.rb:135:in `with_frame'
sass (3.5.6) lib/sass/stack.rb:79:in `with_base'
sass (3.5.6) lib/sass/tree/visitors/perform.rb:162:in `visit'
sass (3.5.6) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
sass (3.5.6) lib/sass/tree/visitors/base.rb:52:in `map'
sass (3.5.6) lib/sass/tree/visitors/base.rb:52:in `visit_children'
sass (3.5.6) lib/sass/tree/visitors/perform.rb:171:in `block in visit_children'
sass (3.5.6) lib/sass/tree/visitors/perform.rb:183:in `with_environment'
sass (3.5.6) lib/sass/tree/visitors/perform.rb:170:in `visit_children'
sass (3.5.6) lib/sass/tree/visitors/base.rb:36:in `block in visit'
sass (3.5.6) lib/sass/tree/visitors/perform.rb:190:in `visit_root'
sass (3.5.6) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.5.6) lib/sass/tree/visitors/perform.rb:161:in `visit'
sass (3.5.6) lib/sass/tree/visitors/perform.rb:10:in `visit'
sass (3.5.6) lib/sass/tree/root_node.rb:36:in `css_tree'
sass (3.5.6) lib/sass/tree/root_node.rb:20:in `render'
sass (3.5.6) lib/sass/engine.rb:290:in `render'
sass-rails (5.0.7) lib/sass/rails/template.rb:47:in `evaluate'
tilt (2.0.8) lib/tilt/template.rb:109:in `render'
sprockets (3.7.1) lib/sprockets/legacy_tilt_processor.rb:25:in `call'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.7.1) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.7.1) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.7.1) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
sprockets (3.7.1) lib/sprockets/loader.rb:44:in `load'
sprockets (3.7.1) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.7.1) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.7.1) lib/sprockets/bundle.rb:23:in `block in call'
sprockets (3.7.1) lib/sprockets/utils.rb:200:in `dfs'
sprockets (3.7.1) lib/sprockets/bundle.rb:24:in `call'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.7.1) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.7.1) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.7.1) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
sprockets (3.7.1) lib/sprockets/loader.rb:44:in `load'
sprockets (3.7.1) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.7.1) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.7.1) lib/sprockets/base.rb:66:in `find_asset'
sprockets (3.7.1) lib/sprockets/base.rb:73:in `find_all_linked_assets'
sprockets (3.7.1) lib/sprockets/manifest.rb:142:in `block in find'
sprockets (3.7.1) lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
sprockets (3.7.1) lib/sprockets/path_utils.rb:228:in `block in stat_tree'
sprockets (3.7.1) lib/sprockets/path_utils.rb:212:in `block in stat_directory'
sprockets (3.7.1) lib/sprockets/path_utils.rb:209:in `each'
sprockets (3.7.1) lib/sprockets/path_utils.rb:209:in `stat_directory'
sprockets (3.7.1) lib/sprockets/path_utils.rb:227:in `stat_tree'
sprockets (3.7.1) lib/sprockets/legacy.rb:105:in `each'
sprockets (3.7.1) lib/sprockets/legacy.rb:105:in `block in logical_paths'
sprockets (3.7.1) lib/sprockets/legacy.rb:104:in `each'
sprockets (3.7.1) lib/sprockets/legacy.rb:104:in `logical_paths'
sprockets (3.7.1) lib/sprockets/manifest.rb:140:in `find'
sprockets-rails (3.2.1) lib/sprockets/railtie.rb:50:in `each'
sprockets-rails (3.2.1) lib/sprockets/railtie.rb:50:in `map'
sprockets-rails (3.2.1) lib/sprockets/railtie.rb:50:in `precompiled_assets'
sprockets-rails (3.2.1) lib/sprockets/railtie.rb:35:in `asset_precompiled?'
sprockets-rails (3.2.1) lib/sprockets/railtie.rb:251:in `block (3 levels) in <class:Railtie>'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:359:in `precompiled?'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:363:in `raise_unless_precompiled_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:337:in `digest_path'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:325:in `asset_path'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:102:in `block in resolve_asset_path'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:241:in `each'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:241:in `detect'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:241:in `resolve_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:101:in `resolve_asset_path'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:79:in `compute_asset_path'
actionview (5.2.0) lib/action_view/helpers/asset_url_helper.rb:200:in `asset_path'
actionview (5.2.0) lib/action_view/helpers/asset_url_helper.rb:375:in `image_path'
actionview (5.2.0) lib/action_view/helpers/asset_tag_helper.rb:467:in `resolve_image_source'
actionview (5.2.0) lib/action_view/helpers/asset_tag_helper.rb:337:in `image_tag'
active_scaffold (3.5.1) lib/active_scaffold/helpers/view_helpers.rb:65:in `loading_indicator_tag'
active_scaffold (3.5.1) app/views/active_scaffold_overrides/_list_header.html.erb:5:in `___sers_bfd__rbenv_versions_______lib_ruby_gems_______gems_active_scaffold_______app_views_active_scaffold_overrides__list_header_html_erb___4564118004616209214_70252748093920'
actionview (5.2.0) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.0) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.0) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.0) lib/action_view/template.rb:157:in `render'
actionview (5.2.0) lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
actionview (5.2.0) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.0) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.2.0) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
actionview (5.2.0) lib/action_view/renderer/partial_renderer.rb:333:in `render_partial'
actionview (5.2.0) lib/action_view/renderer/partial_renderer.rb:312:in `render'
actionview (5.2.0) lib/action_view/renderer/renderer.rb:49:in `render_partial'
actionview (5.2.0) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.2.0) lib/action_view/helpers/rendering_helper.rb:34:in `render'
active_scaffold (3.5.1) lib/active_scaffold/extensions/action_view_rendering.rb:77:in `render'
active_scaffold (3.5.1) app/views/active_scaffold_overrides/_list_with_header.html.erb:3:in `block in ___sers_bfd__rbenv_versions_______lib_ruby_gems_______gems_active_scaffold_______app_views_active_scaffold_overrides__list_with_header_html_erb___3679866165186405245_70252748224980'
actionview (5.2.0) lib/action_view/helpers/capture_helper.rb:41:in `block in capture'
actionview (5.2.0) lib/action_view/helpers/capture_helper.rb:205:in `with_output_buffer'
actionview (5.2.0) lib/action_view/helpers/capture_helper.rb:41:in `capture'
actionview (5.2.0) lib/action_view/helpers/tag_helper.rb:272:in `content_tag'
active_scaffold (3.5.1) app/views/active_scaffold_overrides/_list_with_header.html.erb:1:in `___sers_bfd__rbenv_versions_______lib_ruby_gems_______gems_active_scaffold_______app_views_active_scaffold_overrides__list_with_header_html_erb___3679866165186405245_70252748224980'
actionview (5.2.0) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.0) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.0) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.0) lib/action_view/template.rb:157:in `render'
actionview (5.2.0) lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
actionview (5.2.0) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.0) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.2.0) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
actionview (5.2.0) lib/action_view/renderer/partial_renderer.rb:333:in `render_partial'
actionview (5.2.0) lib/action_view/renderer/partial_renderer.rb:312:in `render'
actionview (5.2.0) lib/action_view/renderer/renderer.rb:49:in `render_partial'
actionview (5.2.0) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.2.0) lib/action_view/helpers/rendering_helper.rb:34:in `render'
active_scaffold (3.5.1) lib/active_scaffold/extensions/action_view_rendering.rb:77:in `render'
active_scaffold (3.5.1) app/views/active_scaffold_overrides/list.html.erb:1:in `___sers_bfd__rbenv_versions_______lib_ruby_gems_______gems_active_scaffold_______app_views_active_scaffold_overrides_list_html_erb___265773930073518046_70252748351320'
actionview (5.2.0) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.0) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.0) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.0) lib/action_view/template.rb:157:in `render'
actionview (5.2.0) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (5.2.0) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.0) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.2.0) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
actionview (5.2.0) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (5.2.0) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (5.2.0) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.2.0) lib/action_view/renderer/template_renderer.rb:16:in `render'
actionview (5.2.0) lib/action_view/renderer/renderer.rb:44:in `render_template'
actionview (5.2.0) lib/action_view/renderer/renderer.rb:25:in `render'
actionview (5.2.0) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.2.0) lib/action_controller/metal/streaming.rb:219:in `_render_template'
actionview (5.2.0) lib/action_view/rendering.rb:84:in `render_to_body'
actionpack (5.2.0) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.2.0) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.2.0) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (5.2.0) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.2.0) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
activesupport (5.2.0) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/Users/bfd/.rbenv/versions/2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
activesupport (5.2.0) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (5.2.0) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
actionpack (5.2.0) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.2.0) lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
actionpack (5.2.0) lib/action_controller/metal/instrumentation.rb:45:in `render'
active_scaffold (3.5.1) lib/active_scaffold/extensions/action_controller_rendering.rb:14:in `render'
active_scaffold (3.5.1) lib/active_scaffold/actions/list.rb:37:in `list_respond_to_html'
active_scaffold (3.5.1) lib/active_scaffold/actions/core.rb:438:in `block (3 levels) in respond_to_action'
actionpack (5.2.0) lib/action_controller/metal/mime_responds.rb:203:in `respond_to'
active_scaffold (3.5.1) lib/active_scaffold/actions/core.rb:434:in `respond_to_action'
active_scaffold (3.5.1) lib/active_scaffold/actions/list.rb:30:in `list'
active_scaffold (3.5.1) lib/active_scaffold/actions/list.rb:12:in `index'
actionpack (5.2.0) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.0) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.0) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.0) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.0) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.0) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.0) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.0) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.0) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.0) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.0) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.0) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.0) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.0) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.0) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:840:in `call'
rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
actionpack (5.2.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.0) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.0) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.6.2) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by duderonomy** [comment]
Saw your comment in issue #595.
Added to Gemfile:
gem 'jquery-rails'

/users route now shows the table.

Many thanks for your assistance.

**Comment by scambra** [comment]
added instructions to readme
