### ISSUE TITLE
rails 5.2.0 has_many relation edit broken

### ISSUE THREAD

**Issue by yisizawa** [activescaffold/active_scaffold#600]
# environment

active_scaffold: master e222bcc5083b99f0420dae5629dd69e1cb3194ba
rails: 5.2.0

### app/assets/javascripts/application.js

```js
//= require jquery
//= require jquery_ujs
//= require active_scaffold
//= require turbolinks
//= require_tree .
```

### app/models/user.rb

```ruby
class User < ApplicationRecord
  has_many :items
end
```

### app/models/item.rb

```ruby
class Item < ApplicationRecord
  belongs_to :user
end
```

# step
1. click http://localhost:3000/items/1/edit?adapter=_list_inline_adapter

or

1. click http://localhost:3000/users/1/edit?adapter=_list_inline_adapter

![items](https://user-images.githubusercontent.com/24412698/43406415-211c32d8-9457-11e8-8ed9-fdea5d5638e4.png)

# stacktrace

```
Started GET "/items/1/edit?adapter=_list_inline_adapter" for 127.0.0.1 at 2018-07-31 00:02:11 +0900
   (2.5ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  ↳ $HOME/.rvm/gems/ruby-2.5.1@rails52/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
Processing by ItemsController#edit as JS
  Parameters: {"adapter"=>"_list_inline_adapter", "id"=>"1"}
  Item Load (0.9ms)  SELECT  "items".* FROM "items" WHERE "items"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ $HOME/.rvm/gems/ruby-2.5.1@rails52/bundler/gems/active_scaffold-e222bcc5083b/lib/active_scaffold/finder.rb:399
  Rendered $HOME/.rvm/gems/ruby-2.5.1@rails52/bundler/gems/active_scaffold-e222bcc5083b/app/views/active_scaffold_overrides/_form_messages.html.erb (2.4ms)
  Rendered $HOME/.rvm/gems/ruby-2.5.1@rails52/bundler/gems/active_scaffold-e222bcc5083b/app/views/active_scaffold_overrides/_form_association.html.erb (14.3ms)
  Rendered $HOME/.rvm/gems/ruby-2.5.1@rails52/bundler/gems/active_scaffold-e222bcc5083b/app/views/active_scaffold_overrides/_form.html.erb (93.1ms)
  Rendered $HOME/.rvm/gems/ruby-2.5.1@rails52/bundler/gems/active_scaffold-e222bcc5083b/app/views/active_scaffold_overrides/_base_form.html.erb (121.4ms)
  Rendered $HOME/.rvm/gems/ruby-2.5.1@rails52/bundler/gems/active_scaffold-e222bcc5083b/app/views/active_scaffold_overrides/_update_form.html.erb (151.7ms)
Completed 500 Internal Server Error in 205ms (ActiveRecord: 4.4ms)



ActionView::Template::Error (wrong number of arguments (given 1, expected 0)):
    1: <%
    2: associated = column.association.singular? ? [parent_record.send(column.name)].compact : parent_record.send(column.name).to_a
    3: if column.show_blank_record?(associated)
    4:   show_blank_record = build_associated(column.association, parent_record)
    5: end

$HOME/.rvm/gems/ruby-2.5.1@rails52/bundler/gems/active_scaffold-e222bcc5083b/lib/active_scaffold/tableless.rb:54:in `skip_statement_cache?'
/usractiverecord (5.2.0) lib/active_record/associations/singular_association.rb:41:in `find_target'
/usractiverecord (5.2.0) lib/active_record/associations/association.rb:151:in `load_target'
/usractiverecord (5.2.0) lib/active_record/associations/association.rb:47:in `reload'
/usractiverecord (5.2.0) lib/active_record/associations/singular_association.rb:9:in `reader'
/usractiverecord (5.2.0) lib/active_record/associations/builder/association.rb:108:in `user'
```

**Comment by scambra** [comment]
Backtrace is failing in tableless. Are you using activerecord models or tableless ones? In your example I see only 2 models, inheriting from ApplicationRecord, but error is in tableless, which I don't see in your example

**Comment by yisizawa** [comment]
I use rails 5.2.0 default generated file.

### app/models/application_record.rb

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
```

**Comment by scambra** [comment]
I have a fix for this error but other tests are failing with rails 5.2.0. I will commit when tests pass with rails 5.2.0

**Comment by yisizawa** [comment]
Thank you!
