### ISSUE TITLE
jquery/active_scaffold.js breaks uglifier

### ISSUE THREAD

**Issue by ConfusedVorlon** [activescaffold/active_scaffold#608]
`jquery/active_scaffold.js` breaks uglifier

when using uglifier in the asset pipeline, procompilation (or compilation on deployment) fails
`rails assets:precompile RAILS_ENV=production` 

(with production.rb having `config.assets.js_compressor = :uglifier`)

excluding `jquery/active_scaffold.js` from active_scaffold.js.erb fixes this. Someone with better js skills would have to dig into where the issue is within `jquery/active_scaffold.js `

the uglifier error is unhelpful

```
Uglifier::Error: Invalid assignment
/Users/rob/.rvm/gems/ruby-2.4.0/gems/uglifier-4.1.20/lib/uglifier.rb:234:in `parse_result'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/uglifier-4.1.20/lib/uglifier.rb:216:in `run_uglifyjs'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/uglifier-4.1.20/lib/uglifier.rb:168:in `compile'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:53:in `call'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:28:in `call'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/railties-5.2.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/railties-5.2.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/railties-5.2.2/lib/rails/command.rb:48:in `invoke'
/Users/rob/.rvm/gems/ruby-2.4.0/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

```

**Comment by scambra** [comment]
Latest fix in active_scaffold.js is using destructuring assignment, a feature from ES6, not supported by uglifier, unless harmony is enabled, although it works in most browsers.
Using Uglifier.new(harmony: true) instead of :uglifier works

However, I have changed to multiple assignments, because it's only ES6 feature used in active_scaffold, so it keeps working with uglifier by default.

**Comment by ConfusedVorlon** [comment]
splendid - thank you

on a slightly related note; It would be great to get an official release out that supports rails 5.2. I'm currently using master which is sub-optimal.
