### ISSUE TITLE
NoMethodError: undefined method `name' for :if:Symbol

### ISSUE THREAD

**Issue by gregschmit** [activescaffold/active_scaffold#659]
I get this error and it appears to be a bug in active scaffold where it's iterating over specific columns, like list or export columns, and rather than iterating over column objets, it's iterating over symbols. I think it's fixable with a PR that I'll attach momentarily, changing this line in `lib/active_scaffold/actions/list.rb:72` from:

    send(:"#{action}_columns")

to:

    send(:"#{action}_columns").map { |c| active_scaffold_config.columns[c] }

Not sure if there is a better or more general way to do this, but I'll submit a PR if not.

Traceback (most relevant part at the top):

```
Error:
Admin::Scaffolds::UplinkAssignmentsControllerTest#test_: Admin::Scaffolds::UplinkAssignmentsController should download export files. :
NoMethodError: undefined method `includes' for :ip:Symbol
    vendor/cache/active_scaffold-810e1fe4d1b6/lib/active_scaffold/actions/list.rb:76:in `block in set_includes_for_columns'
    vendor/cache/active_scaffold-810e1fe4d1b6/lib/active_scaffold/actions/list.rb:76:in `select'
    vendor/cache/active_scaffold-810e1fe4d1b6/lib/active_scaffold/actions/list.rb:76:in `set_includes_for_columns'
    active_scaffold_export (3.4.0) lib/active_scaffold/actions/export.rb:36:in `export'
    actionpack (5.2.4.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
    actionpack (5.2.4.4) lib/abstract_controller/base.rb:194:in `process_action'
    actionpack (5.2.4.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
    actionpack (5.2.4.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    activesupport (5.2.4.4) lib/active_support/callbacks.rb:109:in `block in run_callbacks'
    vendor/cache/active_scaffold-810e1fe4d1b6/lib/active_scaffold/actions/core.rb:311:in `clear_storage'
    activesupport (5.2.4.4) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
    activesupport (5.2.4.4) lib/active_support/callbacks.rb:136:in `run_callbacks'
    actionpack (5.2.4.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
    actionpack (5.2.4.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
    actionpack (5.2.4.4) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
    activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `block in instrument'
    activesupport (5.2.4.4) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
    activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `instrument'
    actionpack (5.2.4.4) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
    actionpack (5.2.4.4) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
    activerecord (5.2.4.4) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
    actionpack (5.2.4.4) lib/abstract_controller/base.rb:134:in `process'
    actionview (5.2.4.4) lib/action_view/rendering.rb:32:in `process'
    actionpack (5.2.4.4) lib/action_controller/metal.rb:191:in `dispatch'
    actionpack (5.2.4.4) lib/action_controller/test_case.rb:517:in `process'
    rails-controller-testing (1.0.5) lib/rails/controller/testing/template_assertions.rb:62:in `process'
    actionpack (5.2.4.4) lib/action_controller/test_case.rb:395:in `get'
    test/controllers/admin/scaffolds/uplink_assignments_controller_test.rb:62:in `block in <class:UplinkAssignmentsControllerTest>'
    test/controllers/admin/scaffolds/uplink_assignments_controller_test.rb:74:in `instance_exec'
    test/controllers/admin/scaffolds/uplink_assignments_controller_test.rb:74:in `block in create_test_from_should_hash'
    minitest (5.14.3) lib/minitest/test.rb:98:in `block (3 levels) in run'
    minitest (5.14.3) lib/minitest/test.rb:195:in `capture_exceptions'
    minitest (5.14.3) lib/minitest/test.rb:95:in `block (2 levels) in run'
    minitest (5.14.3) lib/minitest.rb:272:in `time_it'
    minitest (5.14.3) lib/minitest/test.rb:94:in `block in run'
    minitest (5.14.3) lib/minitest.rb:367:in `on_signal'
    minitest (5.14.3) lib/minitest/test.rb:211:in `with_info_handler'
    minitest (5.14.3) lib/minitest/test.rb:93:in `run'
    minitest (5.14.3) lib/minitest.rb:1029:in `run_one_method'
    minitest (5.14.3) lib/minitest.rb:341:in `run_one_method'
    minitest (5.14.3) lib/minitest.rb:328:in `block (2 levels) in run'
    minitest (5.14.3) lib/minitest.rb:327:in `each'
    minitest (5.14.3) lib/minitest.rb:327:in `block in run'
    minitest (5.14.3) lib/minitest.rb:367:in `on_signal'
    minitest (5.14.3) lib/minitest.rb:354:in `with_info_handler'
    minitest (5.14.3) lib/minitest.rb:326:in `run'
    railties (5.2.4.4) lib/rails/test_unit/line_filtering.rb:10:in `run'
    minitest (5.14.3) lib/minitest.rb:164:in `block in __run'
    minitest (5.14.3) lib/minitest.rb:164:in `map'
    minitest (5.14.3) lib/minitest.rb:164:in `__run'
    minitest (5.14.3) lib/minitest.rb:141:in `run'
    minitest (5.14.3) lib/minitest.rb:68:in `block in autorun'
```

**Comment by scambra** [comment]
I think export_columns method should be fixed to return array of columns, which is what is expected. The only "#{action}_columns" method which exists in ActiveScaffold is list_columns, and it returns array of columns, not symbols.

ActiveScaffoldExport defines export_columns, and it returns array of columns too:

```ruby
    def export_columns
      return @export_columns if defined? @export_columns
      @export_columns = active_scaffold_config.export.columns.reject { |col| params[:export_columns][col.to_sym].nil? }
      sorting = active_scaffold_config.list.user.sorting || active_scaffold_config.list.sorting
      sorting_columns = sorting.reject { |col, _| @export_columns.include?(col.name) }.map(&:first)
      @export_columns.map! { |col| active_scaffold_config.columns[col] }
      @export_columns += sorting_columns
    end
```

**Comment by gregschmit** [comment]
Oh, you might be right, it might've been an override that we had in our app, I will verify and close this if that's the case.

**Comment by gregschmit** [comment]
yep you were right, thanks!
