### ISSUE TITLE
Rails 6: last_template undefined on ActionView::PathSet

### ISSUE THREAD

**Issue by gregschmit** [activescaffold/active_scaffold#662]
I am upgrading a Rails app to Rails 6 and noticed this error that seems to come from ActiveScaffold:

```
	 1: from /Users/gns/git/rxg/console/app/models/custom_email.rb:1368:in `render'
/Users/gns/git/rxg/console/vendor/cache/active_scaffold-810e1fe4d1b6/lib/active_scaffold/extensions/action_view_rendering.rb:84:in `render': undefined method `last_template' for #<ActionView::PathSet:0x00007fd300417488> (NoMethodError)
```

**Comment by gregschmit** [comment]
I removed my manually created ActionView::Base, and this no longer conflicted.
