### ISSUE TITLE
Hash#index has been removed from at least Ruby >= 2.7

### ISSUE THREAD

**Issue by xn** [activescaffold/active_scaffold#687]
Hash#index has been removed from at least Ruby >= 2.7

use Hash#key instead.

Freedom Patch:
```
class Hash
  def index(k)
    key(k)
  end
end
```

```
ActionView::Template::Error (undefined method `index' for {/%a/=>"D", /%A/=>"DD", /%b/=>"M", /%B/=>"MM", /%d/=>"dd", /%e|%-d/=>"d", /%j/=>"oo", /%m/=>"mm", /%-m|%-m/=>"m", /%y/=>"y", /%Y/=>"yy", /%H/=>"HH", /%I/=>"hh", /%M/=>"mm", /%p/=>"tt", /%S/=>"ss", /%z/=>"z", /%[cUWwxXZ]/=>""}:Hash

        unsupported = DATE_FORMAT_CONVERSION.index ''
                                            ^^^^^^
Did you mean?  index_by):

active_scaffold (73224f613631) lib/active_scaffold/bridges/date_picker/helper.rb:86:in `to_datepicker_format'
active_scaffold (73224f613631) lib/active_scaffold/bridges/date_picker/helper.rb:51:in `date_options'
active_scaffold (73224f613631) lib/active_scaffold/bridges/date_picker/helper.rb:27:in `block in date_options_for_locales'
active_scaffold (73224f613631) lib/active_scaffold/bridges/date_picker/helper.rb:26:in `collect'
active_scaffold (73224f613631) lib/active_scaffold/bridges/date_picker/helper.rb:26:in `date_options_for_locales'
active_scaffold (73224f613631) lib/active_scaffold/bridges/date_picker.rb:23:in `localization'
active_scaffold (73224f613631) app/assets/javascripts/jquery/date_picker_bridge.js.erb:3:in `call'
```
https://github.com/activescaffold/active_scaffold/blob/0c2383d7cab00993556740abd8bf764e56ecb6f2/lib/active_scaffold/bridges/date_picker/helper.rb#L86

**Comment by scambra** [comment]
Fixed in master branch
