### ISSUE TITLE
NameError when rendering a scaffold whose controller name doesn't match the underlying model

### ISSUE THREAD

**Issue by moracca** [activescaffold/active_scaffold#711]
There are some instances where a scaffold controller has a different name than the underlying model that the scaffold references.  For example, there might be several types of Policy records that are all stored within a single "Policy" model, but have different scaffold configurations with different columns etc.

simplified example:
```
class Admin::Scaffolds::TriggerPoliciesController < Admin::ScaffoldsController
  active_scaffold :policy do |config|
    config.label = "Trigger Policies"
  end
end
```
```
class Admin::Scaffolds::FilterPoliciesController < Admin::ScaffoldsController
  active_scaffold :policy do |config|
    config.label = "Filter Policies"
  end
end
```

The expectation is that this scaffold renders, using Policy as the model, but TriggerPoliciesController for the controller class's active scaffold config, and in turn the config.label value configured in that controller.

The actual result is that an exception is encountered when it is trying to determine the label for the scaffold (unless a label is passed in the render_scaffold arguments).

This is because when determining the label, if it was not passed in the render_scaffold arguments, it is found by parsing the model name from the controller path, which may not actually be the same as the model that the scaffold is using.

extensions/action_view_rendering.rb:
```
        content_tag(:div, :id => id, :class => 'active-scaffold-component', :data => {:refresh => url}) do
          # parse the ActiveRecord model name from the controller path, which
          # might be a namespaced controller (e.g., 'admin/admins')
          model = remote_controller.to_s.sub(%r{.*/}, '').singularize
          content_tag(:div, :class => 'active-scaffold-header') do
            content_tag(:h2) do
              link_label = options[:label] || active_scaffold_config_for(model).list.label
              link_to(link_label, url, remote: true, class: 'load-embedded', data: {error_msg: as_(:error_500)}) <<
                loading_indicator_tag(url_options)
            end
          end
        end
```
When the scaffold controller doesn't match the model, we end up with a NameError when we eventually try to constantize "FilterPolicy" (it should actually be "Policy").

My proposal:

Would it be possible instead to find the `active_scaffold_config` the specific controller we are using, as opposed to using active_scaffold_config_for(model)?  

Off the top of my head it could look something like this, but I'm open to other suggestions too..  maybe there's  a better way to infer the controller class name..
```
        url = url_for(url_options)
        content_tag(:div, :id => id, :class => 'active-scaffold-component', :data => {:refresh => url}) do
          content_tag(:div, :class => 'active-scaffold-header') do

            label = options[:label] || begin
              # attempt to retrieve the active_scaffold_config by constantizing
              # the controller path
              controller_config = "#{remote_controller}_controller".camelize.constantize.active_scaffold_config rescue nil
              controller_config.try(:label) || begin
                # if we couldn't determine the controller config by instantiating the
                # controller class, parse the ActiveRecord model name from the
                # controller path, which might be a namespaced controller (e.g., 'admin/admins')
                model = remote_controller.to_s.sub(%r{.*/}, '').singularize
                active_scaffold_config_for(model).list.label
              end
            end
            
            content_tag(:h2) do
              link_to(label, url, remote: true, class: 'load-embedded', data: {error_msg: as_(:error_500)}) <<
                loading_indicator_tag(url_options)
            end
          end
        end
```

**Comment by scambra** [comment]
The code you posted from lib/active_scaffold/extensions/action_view_rendering.rb is used for calls like `render active_scaffold: controller_name`, doesn't use active_scaffold_config_for, so you should use `render active_scaffold: 'admin/scaffolds/filter_policies'`

ActiveScaffold uses active_scaffold_controller_for with a model to find the controller for has_many associations, for example. When ActiveScaffold can't guess the controller for a model, the method can be overrided in the controller, or any parent controller such as ApplicationController, as explained in the wiki: https://github.com/activescaffold/active_scaffold/wiki/API%3A-Core#active_scaffold_controller_for-override-method

**Comment by moracca** [comment]
Here is the backtrace of the exception if it helps
```
activesupport (7.0.4) lib/active_support/inflector/methods.rb:280:in `constantize'
activesupport (7.0.4) lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
vendor/cache/active_scaffold-404500d2f3f2/lib/active_scaffold/config/core.rb:283:in `model'
vendor/cache/active_scaffold-404500d2f3f2/lib/active_scaffold/orm_checks.rb:95:in `block (2 levels) in <module:OrmChecks>'
vendor/cache/active_scaffold-404500d2f3f2/lib/active_scaffold/config/core.rb:173:in `initialize'
active_scaffold_sortable (3.3.8) lib/active_scaffold_sortable/core.rb:4:in `initialize'
vendor/cache/active_scaffold-404500d2f3f2/lib/active_scaffold/bridges/active_storage/active_storage_bridge.rb:6:in `initialize'
vendor/cache/active_scaffold-404500d2f3f2/lib/active_scaffold/core.rb:217:in `new'
vendor/cache/active_scaffold-404500d2f3f2/lib/active_scaffold/core.rb:217:in `rescue in active_scaffold_config_for'
vendor/cache/active_scaffold-404500d2f3f2/lib/active_scaffold/core.rb:214:in `active_scaffold_config_for'
vendor/cache/active_scaffold-404500d2f3f2/lib/active_scaffold/helpers/controller_helpers.rb:19:in `active_scaffold_config_for'
vendor/cache/active_scaffold-404500d2f3f2/lib/active_scaffold/helpers/controller_helpers.rb:8:in `active_scaffold_config_for'
vendor/cache/active_scaffold-404500d2f3f2/lib/active_scaffold/extensions/action_view_rendering.rb:152:in `block (3 levels) in render_embedded'
actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `capture'
actionview (7.0.4) lib/action_view/helpers/tag_helper.rb:371:in `content_tag'
vendor/cache/active_scaffold-404500d2f3f2/lib/active_scaffold/extensions/action_view_rendering.rb:151:in `block (2 levels) in render_embedded'
actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `capture'
actionview (7.0.4) lib/action_view/helpers/tag_helper.rb:371:in `content_tag'
vendor/cache/active_scaffold-404500d2f3f2/lib/active_scaffold/extensions/action_view_rendering.rb:150:in `block in render_embedded'
actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `capture'
actionview (7.0.4) lib/action_view/helpers/tag_helper.rb:371:in `content_tag'
vendor/cache/active_scaffold-404500d2f3f2/lib/active_scaffold/extensions/action_view_rendering.rb:146:in `render_embedded'
vendor/cache/active_scaffold-404500d2f3f2/lib/active_scaffold/extensions/action_view_rendering.rb:40:in `render'
app/helpers/admin_helper.rb:22:in `block in render_scaffold'
actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `capture'
actionview (7.0.4) lib/action_view/helpers/tag_helper.rb:371:in `content_tag'
app/helpers/admin_helper.rb:18:in `render_scaffold'
app/views/admin/menu/administrators.html.erb:7
```

**Comment by scambra** [comment]
Sorry you're right, as the helper is getting a controller path, it would be better to get the controller class from it, instead of guessing the model from controller path and then call active_scaffold_config_for

**Comment by scambra** [comment]
Could you send a PR with your proposed change?

**Comment by moracca** [comment]
I think the pr linked to this issue has the fix needed.
https://github.com/activescaffold/active_scaffold/pull/712

**Comment by scambra** [comment]
I saw it later, thanks, I have merged it
